blank_issues_enabled: false
contact_links:
  - name: Legacy Modding Discord
    url: https://discord.gg/EXshrPV
    about: >-
      The Discord channel that houses channels for Et Futurum Requiem and is your one-stop-shop for any legacy version between 1.3 up to the latest unsupported version.